language: generic

services:
  - docker

env:
  matrix:
    - BASE="centos" KONG_DOCKER_TAG="kong-centos"
    - BASE="alpine" KONG_DOCKER_TAG="kong-alpine"
    - BASE="ubuntu" KONG_DOCKER_TAG="kong-ubuntu"
    - BASE="rhel" KONG_DOCKER_TAG="kong-rhel"

before_script:
  - make build
script:
  - make test

jobs:
  include:
    - stage: deploy
      env:
        - BASE=rhel
        - KONG_DOCKER_TAG=kong-rhel
        - TAG=$TRAVIS_TAG
      script: make release-rhel
      if: tag IS present
